spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_demo
    username: root
    password: paudel123
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  application:
    name: Employee-Service
server:
  port: 8082