server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rating-service
    username: postgres
    password: Paudel123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: Hotel-Service
  config:
      import: optional:configserver:http://localhost:8085
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka